---
title: "Client Report - Baseball Database SQL Query"
subtitle: "Unit 3 Task 2"
author: "Gavin Blair"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---


```{python}
import polars as pl
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

## QUESTION 1

__Write an SQL query that provides playerID, yearID, and batting average for players with at least 1 at bat that year. Sort the table from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

_The first one was in 1957, and the most recent was in 2019._

```{python}
# Include and execute your code here

# The code below can serve as a template for all the rest of your queries. It is just missing the
# SQL code. Put your SQL query in between the triple quotation marks to create the query. The records will be stored in 'results', which is a polars data frame

q = """
SELECT
    playerID,
    yearID,
    CAST(H AS FLOAT) / AB AS batting_average
FROM Batting
WHERE AB >= 1
ORDER BY batting_average DESC, playerID ASC
LIMIT 5
"""

results = pl.read_database(q, con)
results


```


## QUESTION 2

__Use the same query as above, but only include players with at least 10 at bats that year. Print the top 5 results.__  

_The people that had at least 10 bats all had a batting average of over 50%._

```{python}
# Include and execute your code here
q = """
SELECT
    playerID,
    yearID,
    CAST(H AS FLOAT) / AB AS batting_average
FROM Batting
WHERE AB >= 10
ORDER BY batting_average DESC, playerID ASC
LIMIT 5
"""

results = pl.read_database(q, con)
results

```


## QUESTION 3

__Now modify the SQL query to calculate the batting average for players over their entire careers (all years combined). Only include players with at least 100 at bats over their entire career, and print the top 5 results.__

_People with over 100 at bats tended to have batting averages of less than 50%._

```{python}
# Include and execute your code here
q = """
SELECT
    playerID,
    SUM(H) * 1.0 / SUM(AB) AS career_batting_average
FROM Batting
GROUP BY playerID
HAVING SUM(AB) >= 100
ORDER BY career_batting_average DESC, playerID ASC
LIMIT 5
"""

results = pl.read_database(q, con)
results

```