---
title: "Client Report - Missing values"
subtitle: "Unit 2 Task 3"
author: "Gavin Blair"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```

## QUESTION 1

1. __Convert values to missing__ Start with a fresh copy of the flights dataset by reading it in from the link provided above (as opposed to starting with the dataset you ended with in the last assignment). Identify data values that are problematic, non-sense or impossible and change them to be missing. In your report include one record example (one row) from your clean data, in the raw JSON format. Your example should display at least one missing value so that we can verify it was done correctly. (Note: JSON will convert NaN's to null). Describe your process for finding values that needed to be changed, and how you changed them.

__If the number for the number of delays for a carrier or the number of delays for a late aircraft is -999, it should be converted to a missing value.__

```{python}
# Include and execute your code here
df_clean = (
  df.with_columns(
    pl.col("num_of_delays_carrier")
    .replace("1500+", None)
    .cast(pl.Int64),
    pl.col("num_of_delays_late_aircraft")
    .replace(-999, None),
    pl.col("minutes_delayed_carrier")
    .replace(-999, None)
  )
)

minutes_col = [col for col in df_clean.columns if col.startswith("minutes_delayed")]
nums_cols = [col for col in df_clean.columns if col.startswith("num_of")]

rows_with_missing = df_clean.filter(
    pl.any_horizontal([pl.col(col).is_null() for col in minutes_col + nums_cols])
)

rows_with_missing.head()
```

## QUESTION 2

2. __Filling in missing data__ For all the "minutes_delayed" columns, fill in any missing values with the median of that column. For the "num_of" columns, fill in missing values with that column's mean.

_Nothing to write/report for this question_

```{python}
# Include and execute your code here
minutes_cols = [col for col in df.columns if "minutes_delayed" in col]
num_cols = [col for col in df.columns if "num_of" in col]

df = df.with_columns(
    [
        pl.col(col).cast(pl.Float64, strict=False)
        for col in minutes_cols + num_cols
    ]
)

clean_df = df.with_columns(

    [
        pl.col(col)
        .fill_null(df[col].median())
        .alias(col)
        for col in minutes_cols
    ]

    +

    [
        pl.col(col)
        .fill_null(df[col].mean())
        .alias(col)
        for col in num_cols
    ]
)

clean_df.head()
```

## QUESTION 3
 
3. __Display a histogram for num_of_delays_carrier and for minutes_delayed_nas (2 separate histograms in total). Comment on the shape of each one. Also report the mean of each of these columns now that missing values have been filled in.__

_This was hard to figure out, but the x-axis on the graph is the number of minutes a flight was delayed, and the y-axis is the frequency of flights with that delay. This means that most common number of minutes of a flight getting delayed is around 411, at 61 flights._

```{python}
# Include and execute your code here
means = df.select([
    pl.col("num_of_delays_carrier").mean().alias("mean_num_of_delays_carrier"),
    pl.col("minutes_delayed_nas").mean().alias("mean_minutes_delayed_nas")
])

print(means)

p1 = (
    ggplot({"x": df["num_of_delays_carrier"].to_list()},
           aes(x="x"))
    + geom_histogram(bins=30)
    + ggtitle("Histogram: Number of Carrier Delays")
)

p2 = (
    ggplot({"x": df["minutes_delayed_nas"].to_list()},
           aes(x="x"))
    + geom_histogram(bins=30)
    + ggtitle("Histogram: NAS Delay Minutes")
)

p1 + p2
```